# Use an argument for the base image
ARG BASE_IMAGE=semitechnologies/weaviate:latest
FROM $BASE_IMAGE

# Add custom configuration, schema, or scripts if needed
# COPY your-custom-config /your-config-location