version: '3.8'

services:
  mqtt:
    image: cdaprod/cda-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - type: volume
        source: mqtt_config
        target: /mqtt
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mqtt_config:
    name: mqtt_config_volume