version: '3.8'

services:
  cda-nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro # If using HTTPS
    networks:
      - app_network

networks:
  app_network:
    external: true
