version: '3.8'

services:
  minio:
    image: cdaprod/cda-minio:latest
    container_name: cda_minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    networks:
      - app_network

volumes:
  minio_data:

networks:
  app_network:
    driver: overlay