name: Deploy Services

on:
  dispatch_workflow:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy MinIO Stack
        run: |
          export MINIO_ROOT_USER=${{ secrets.MINIO_ACCESS_KEY }}
          export MINIO_ROOT_PASSWORD=${{ secrets.MINIO_SECRET_KEY }}
          docker stack deploy -c ./minio/docker-compose.minio.yaml minio_stack

      - name: Deploy Weaviate Stack
        run: |
          # Set any environment variables for Weaviate here
          docker stack deploy -c ./weaviate/docker-compose.weaviate.yaml weaviate_stack

      - name: Deploy NGINX Stack
        run: |
          # Set any environment variables for NGINX here
          # docker stack deploy -c ./nginx-server/docker-compose.nginx.yaml nginx_stack
