name: Deploy Services

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy MinIO Stack
        run: |
          export MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}
          export MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}
          docker stack deploy -c ./minio/docker-compose.minio.yaml minio_stack

      - name: Deploy Weaviate Stack
        run: |
          docker stack deploy -c ./weaviate/docker-compose.weaviate.yaml weaviate_stack

      - name: Deploy NGINX Stack
        run: |
          docker stack deploy -c ./nginx/docker-compose.nginx.yaml nginx_stack

      - name: Deploy Jupytee Stack
        run: |
          docker stack deploy -c ./jupyter/docker-compose.jupyter.yaml jupyter_stack