# Setup Runner

name: Deploy to Docker Swarm

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Docker Swarm
        run: |
          docker stack deploy -c docker-compose.yml --with-registry-auth cda-stack
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}